AllSports.WebMVC/Controllers/PlayerController.cs
using AllSports.Data;
using AllSports.Models.PlayerModels;
using AllSports.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AllSports.WebMVC.Controllers
{
    [Authorize]
    public class PlayerController : Controller
    {
        public PlayerService CreatePlayerService()
        {
            var userName = User.Identity.GetUserName();
            var service = new PlayerService(userName);
            return service;
        }
        // GET: Player
        [AllowAnonymous]
        public ActionResult Index()
        {
            PlayerService service = CreatePlayerService();
            var model = service.GetPlayers();
            return View(model);
        }

        public ActionResult Create(string userName)
        {
            List<Team> teams = (new TeamService(userName)).GetTeamsData().ToList();
            var query = from T in teams
                        select new SelectListItem()
                        {
                            Value = T.TeamId.ToString(),
                            Text = T.TeamName
                        };
            ViewBag.TeamId = query.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlayerCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreatePlayerService();

            if (service.CreatePlayer(model))
            {
                TempData["SaveResult"] = $"{model.FirstName} {model.LastName} was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", $"{model.FirstName} {model.LastName} could not be created.");

            return View(model);
        }
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var service = CreatePlayerService();
            var model = service.GetPlayerById(id);

            return View(model);
        }
        [AllowAnonymous]
        [HttpGet, Route("Player/List/id")]
        public ActionResult List(int id)
        {
            var service = CreatePlayerService();
            var model = service.GetPlayersbyTeamId(id);
            return View(model);
        }
        public ActionResult Edit(string userName, int id)
        {
            var player = CreatePlayerService().GetPlayerById(id);
            List<Team> teams = (new TeamService(userName)).GetTeamsData().ToList();
            ViewBag.TeamId = teams.Select(
                T => new SelectListItem()
                {
                    Value = T.TeamId.ToString(),
                    Text = T.TeamName,
                    Selected = player.TeamId == T.TeamId,
                });

            var model =
                new PlayerEdit
                {
                    PlayerId = player.PlayerId,
                    FirstName = player.FirstName,
                    LastName = player.LastName,
                    JerseyNumber = player.JerseyNumber,
                    Height = player.Height,
                    Weight = player.Weight,
                    YearsWithTeam = player.YearsWithTeam,
                    TwitterHandle = player.TwitterHandle,
                    TeamId = player.TeamId
                };

            return View(model);
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PlayerEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.PlayerId != id)
            {
                ModelState.AddModelError("", "Id mismatch");
                return View(model);
            }

            var service = CreatePlayerService();
            if (service.UpdatePlayer(model))
            {
                TempData["SaveResult"] = $"{model.FirstName} {model.LastName}s' information has been updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", $"Unable to update {model.FirstName} {model.LastName}s' information.");
            return View();
        }



        public ActionResult Delete(int id)
        {
            var service = CreatePlayerService();
            var model = service.GetPlayerById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public ActionResult DeletePlayer(int id)
        {
            var service = CreatePlayerService();
            var model = service.GetPlayerById(id);
            service.Delete(id);

            TempData["SaveResult"] = $"{model.FirstName} {model.LastName} has been deleted.";

            return RedirectToAction("Index");

        }
    }
}

AllSports.WebMVC/Views/Player/Create.cshtml
@model AllSports.Models.PlayerModels.PlayerCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Player", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>PlayerCreate</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JerseyNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JerseyNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JerseyNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YearsWithTeam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YearsWithTeam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YearsWithTeam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.College, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.College, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.College, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TwitterHandle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TwitterHandle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TwitterHandle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TeamId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TeamId, ViewBag.TeamId as SelectList, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TeamId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="File" name="File" />
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AllSports.WebMVC/Views/Player/Delete.cshtml
@model AllSports.Models.PlayerModels.PlayerDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player Detail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JerseyNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JerseyNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearsWithTeam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearsWithTeam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.College)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.College)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwitterHandle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwitterHandle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeamId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeamName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AllSports.WebMVC/Views/Player/Details.cshtml
@model AllSports.Models.PlayerModels.PlayerDetail

@{
    ViewBag.Title = "Details";
}

<style>
    div.col-lg-2 {
        float: left;
        top: 50px;
    }
</style>

<h2>Details</h2>
<div class="col-lg-2" id="image">
    @if (Model.Contents != null)
    {
        var base64 = Convert.ToBase64String(Model.Contents); var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        <img src=@imgSrc , class="Postimg" , alt="Player Image" />
    }
    else
    {
        <img src="" class="img-fluid" alt="Player Image" />
    }

    <div>
        <h4>Player Detail</h4>
        <hr />
        <div class="col-lg-12">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FirstName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateOfBirth)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateOfBirth)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Age)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Age)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.JerseyNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JerseyNumber)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Height)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Height)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Weight)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Weight)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.YearsWithTeam)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.YearsWithTeam)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.College)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.College)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TwitterHandle)
                </dt>

                <dd>
                    <a href="@Html.DisplayFor(model => model.TwitterHandle)">@Html.DisplayFor(model => model.TwitterHandle)</a>
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TeamName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TeamName)
                </dd>

            </dl>
        </div>
    </div>
    <p class="action-link">
        @Html.ActionLink("Edit", "Edit", new { id = Model.PlayerId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

AllSports.WebMVC/Views/Player/Edit.cshtml
@model AllSports.Models.PlayerModels.PlayerEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Player", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>PlayerEdit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PlayerId)

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JerseyNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JerseyNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JerseyNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YearsWithTeam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YearsWithTeam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YearsWithTeam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TwitterHandle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TwitterHandle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TwitterHandle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TeamId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TeamId, ViewBag.TeamId as SelectList, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TeamId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="File" name="File" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
}

AllSports.WebMVC/Views/Player/Index.cshtml
@model IEnumerable<AllSports.Models.PlayerModels.PlayerListItem>

@{
    ViewBag.Title = "Index";
}

<h2>All Players</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlayerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JerseyNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlayerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JerseyNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeamName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.PlayerId }) |
                @Html.ActionLink("Details", "Details", new { id = item.PlayerId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.PlayerId })
            </td>
        </tr>
    }

</table>

AllSports.WebMVC/Views/Player/List.cshtml
@model IEnumerable<AllSports.Models.PlayerModels.Team_PlayerListItem>

@{
    ViewBag.Title = "List";
}

<h2>Roster</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlayerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JerseyNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearsWithTeam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.College)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JerseyNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearsWithTeam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.College)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PlayerId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PlayerId}) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PlayerId })
        </td>
    </tr>
}

</table>