AllSports.WebMVC/Controllers/CoachController.cs
using AllSports.Data;
using AllSports.Models.CoachModels;
using AllSports.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AllSports.WebMVC.Controllers
{
    [Authorize]
    public class CoachController : Controller
    {
        public CoachService CreateCoachService()
        {
            var userName = User.Identity.GetUserName();
            var service = new CoachService(userName);

            return service;
        }

        // GET: Coach
        [AllowAnonymous]
        public ActionResult Index()
        {
            var service = CreateCoachService();
            var model = service.GetCoaches();
            return View(model);
        }

        public ActionResult Create(string userName)
        {
            List<Team> Teams = (new TeamService(userName)).GetTeamsData().ToList();
            var query = from T in Teams
                        select new SelectListItem() 
                        { 
                            Value=T.TeamId.ToString(),
                            Text =T.TeamName
                        };
            ViewBag.TeamId = query.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CoachCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateCoachService();

            if (service.CreateCoach(model))
            {
                TempData["SaveResult"] = $"{model.FirstName} {model.LastName} was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", $"{model.FirstName} {model.LastName} could not be created.");

            return View(model);
        }
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var service = CreateCoachService();
            var model = service.GetCoachById(id);
            return View(model);
        }
        [HttpGet, Route("Coach/CoachList/id")]
        public ActionResult CoachList(int id)
        {
            var service = CreateCoachService();
            var model = service.GetCoachesbyTeamId(id);
            return View(model);
        }

        public ActionResult Edit(string userName, int id)
        {
            var coach = CreateCoachService().GetCoachById(id);
            List<Team> Teams = (new TeamService(userName)).GetTeamsData().ToList();
            ViewBag.TeamId = Teams.Select(t => new SelectListItem()
            {
                Value = t.TeamId.ToString(),
                Text= t.TeamName,
                Selected=coach.TeamId == t.TeamId
            }
            );
            var model =
                new CoachEdit
                {
                    CoachId = coach.CoachId,
                    FirstName = coach.FirstName,
                    LastName = coach.LastName,
                    YearsWithTeam = coach.YearsWithTeam,
                    CoachPosition = coach.CoachPosition,
                    TeamId = coach.TeamId
                };

            return View(model);
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CoachEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.CoachId != id)
            {
                ModelState.AddModelError("", "Id mismatch");
                return View(model);
            }

            var service = CreateCoachService();
            if (service.UpdateCoach(model))
            {
                TempData["SaveResult"] = $"{model.FirstName} {model.LastName}s' information has been updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", $"Unable to update {model.FirstName} {model.LastName}s' information.");
            return View();
        }


        public ActionResult Delete(int id)
        {
            var service = CreateCoachService();
            var model = service.GetCoachById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCoach(int id)
        {
            var service = CreateCoachService();
            var model = service.GetCoachById(id);
            service.Delete(id);
            TempData["SaveResult"] = $"{model.FirstName} {model.LastName} has been deleted";

            return RedirectToAction("Index");
        }
    }
}

AllSports.WebMVC/Controllers/FanController.cs
using AllSports.Data;
using AllSports.Models.FanModels;
using AllSports.Models.TeamModels;
using AllSports.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AllSports.WebMVC.Controllers
{
    [Authorize]
    public class FanController : Controller
    {
        public FanService CreateFanService()
        {
            var userName = User.Identity.GetUserName();
            var service = new FanService(userName);
            return service;
        }
        // GET: Fan
        public ActionResult Index()
        {
            var service = CreateFanService();
            var model = service.GetFans();

            return View(model);

        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FanCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateFanService();

            if (service.CreateFan(model))
            {
                TempData["SaveResult"] = $"The Fan {model.FirstName} {model.LastName} was created.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", $"The fan {model.FirstName} {model.LastName} was not created.");

            return View(model);
        }
        [Route("Fan/ConnectFanWithTeam/id")]
        public ActionResult ConnectFanWithTeam(string userName)
        {
            List<Team> Teams = (new TeamService(userName)).GetTeamsData().ToList();
            var query = from T in Teams
                        select new SelectListItem()
                        {
                            Value = T.TeamId.ToString(),
                            Text = T.TeamName
                        };
            ViewBag.TeamId = query.ToList();
            return View();
        }

        [HttpPost]
        [ActionName("ConnectFanWithTeam")]// this must match the name of the method that returns the view
        [ValidateAntiForgeryToken]
        public ActionResult Connect(int id, ConnectFan model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateFanService();
           

            if (service.ConnectFanToTeam(id, model))
            {
                TempData["SaveResult"] = $"You are now a fan of {model.TeamId}";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The model could not be connected.");

            return View(model);
        }

        [HttpGet, Route("Fan/FanList/id")]
        public ActionResult FanList(int id)
        {
            var service = CreateFanService();
            var model = service.GetFansByTeamId(id);
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var service = CreateFanService();
            var model = service.GetFanbyId(id);

            return View(model)
;
        }

        public ActionResult Edit(int id)
        {
            var service = CreateFanService();
            var details = service.GetFanbyId(id);
            var model =
                new FanEdit
                {
                    FanId = details.FanId,
                    FirstName = details.FirstName,
                    LastName = details.LastName,
                    CityName = details.CityName,
                    State = details.State
                };

            return View(model);
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateFan(FanEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateFanService();
            if (service.UpdateFan(model))
            {
                TempData["SaveResult"] = $"{model.FirstName} {model.LastName}s' information has been updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", $"Unable to update {model.FirstName} {model.LastName}s' information.");

            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var service = CreateFanService();
            var model = service.GetFanbyId(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteTeam(int id)
        {
            var service = CreateFanService();
            var model = service.GetFanbyId(id);
            service.Delete(id);
            TempData["SaveResult"] = $"{model.FirstName} {model.LastName} has been deleted.";

            return RedirectToAction("Index");
        }
    }
}

AllSports.WebMVC/Controllers/TeamController.cs
using AllSports.Data;
using AllSports.Models.TeamModels;
using AllSports.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AllSports.WebMVC.Controllers
{
    [Authorize]
    public class TeamController : Controller
    {
        public TeamService CreateTeamService()
        {
            var userName = User.Identity.GetUserName();
            var service = new TeamService(userName);
            return service;
        }
        // GET: League
        [AllowAnonymous]
        public ActionResult Index()
        {
            var service = CreateTeamService();
            var model = service.GetTeams();
            return View(model);
        }

        public ActionResult Create(string username)
        {

            List<League> Leagues = (new LeagueService(username)).GetLeaguesData().ToList();
            var query = from l in Leagues
                        select new SelectListItem()
                        { Value = l.LeagueId.ToString(),
                            Text = l.LeagueName
                        };
            ViewBag.LeagueId = query.ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TeamCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateTeamService();

            if (service.CreateTeam(model))
            {
                TempData["Save Result"] = $"{model.TeamName} was created";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", $"{model.TeamName} could not be created");

            return View(model);
        }

        [HttpGet, Route("Team/GetTeamsByLeague/id")]
        [AllowAnonymous]
        public ActionResult GetTeamsByLeague(int id)
        {
            var service = CreateTeamService();
            var model = service.GetTeamsbyLeagueId(id);
            return View(model);

        }


        [HttpGet, Route("Team/TeamList/id")]
        [AllowAnonymous]
        public ActionResult TeamList(int id)
        {
            var service = CreateTeamService();
            var model = service.GetTeamsByFanId(id);
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var service = CreateTeamService();
            var model = service.GetTeamById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateTeamService();
            var detail = service.GetTeamById(id);
            var model =
                new TeamEdit
                {
                    TeamId = detail.TeamId,
                    TeamName = detail.TeamName,
                    Wins = detail.Wins,
                    Losses = detail.Losses,
                    CityName = detail.CityName,
                    State = detail.State
                };
            return View(model);
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateTeam(TeamEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateTeamService();

            if (service.UpdateTeam(model))
            {
                TempData["SaveResult"] = $"The {model.TeamName} was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", $"Unable to update the {model.TeamName}");
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var service = CreateTeamService();
            var model = service.GetTeamById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public ActionResult DeleteTeam(int id)
        {
            var service = CreateTeamService();
            var model = service.GetTeamById(id);
            service.Delete(id);
            TempData["SaveResult"] = $"{model.TeamName} has been deleted.";

            return RedirectToAction("Index");
        }
    }
}

AllSports.WebMVC/Views/Team/Create.cshtml
@model AllSports.Models.TeamModels.TeamCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Team", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TeamCreate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TeamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeamName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wins, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wins, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wins, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Losses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Losses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Losses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeagueId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LeagueId, ViewBag.LeagueId as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeagueId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="form-group">
                @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" id="File" name="File" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>
}

AllSports.WebMVC/Views/Team/Delete.cshtml
@model AllSports.Models.TeamModels.TeamDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Team Detail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TeamName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wins)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wins)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Losses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Losses)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WinPercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WinPercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeagueName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeagueName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AllSports.WebMVC/Views/Team/Details.cshtml
@model AllSports.Models.TeamModels.TeamDetail

@{
    ViewBag.Title = "Details";
}

<style>
    div.col-md-2#image {
        margin-left: 0;
        margin-top: 0;
    }
</style>

<h2>Team Info</h2>


<h4>@Html.DisplayFor(model => model.TeamName) </h4>

<div id="image">

    @if (Model.Contents != null)
    {
        var base64 = Convert.ToBase64String(Model.Contents); var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        <img src=@imgSrc , class="Postimg" , alt="Team Logo" , height="200px" , width="225px" />
    }
    else
    {
        <img src="" class="img-fluid" alt="Team Logo" />
    }
</div>
<hr />
<div>
    <div class="col--lg-12">
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Wins)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Wins)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Losses)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Losses)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CityName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CityName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.State)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.State)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LeagueName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LeagueName)
            </dd>

        </dl>

    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TeamId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AllSports.WebMVC/Views/Team/Edit.cshtml
@model AllSports.Models.TeamModels.TeamEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>



@using (Html.BeginForm("Edit", "Team", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TeamEdit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TeamId)

        <div class="form-group">
            @Html.LabelFor(model => model.TeamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeamName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wins, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wins, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wins, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Losses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Losses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Losses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="File" name="File" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AllSports.WebMVC/Views/Team/GetTeamsByLeague.cshtml
@model IEnumerable<AllSports.Models.TeamModels.League_Team_ListItem>

@{
    ViewBag.Title = "GetTeamsByLeague";
}

<h2>Teams in Leqgue</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Wins)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Losses)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CityName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TeamName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Wins)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Losses)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CityName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TeamId  }) |
            @Html.ActionLink("Details", "Details", new { id=item.TeamId}) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TeamId})
        </td>
    </tr>
}

</table>

AllSports.WebMVC/Views/Team/Index.cshtml
@model IEnumerable<AllSports.Models.TeamModels.TeamListItem>

@{
    ViewBag.Title = "Index";
}

<h2>All Teams</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeamId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SportName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeagueName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TeamId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeamName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SportName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeagueName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.TeamId }) |
                @Html.ActionLink("View Details", "Details", new { id = item.TeamId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.TeamId })
                <br />
                <br />
                @Html.ActionLink("See Players", "List", "Player", new { id=item.TeamId}, null) |
                @Html.ActionLink("See Coaches", "CoachList", "Coach", new { id =item.TeamId}, null) |
                @Html.ActionLink("See Fans", "FanList", "Fan", new {id=item.TeamId }, null)
            </td>
        </tr>
    }

</table>

AllSports.WebMVC/Views/Team/TeamList.cshtml
@model IEnumerable<AllSports.Models.TeamModels.TeamListItem>

@{
    ViewBag.Title = "TeamList";
}

<h2>Team List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeamId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TeamId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TeamName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TeamId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TeamId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TeamId })
        </td>
    </tr>
}

</table>